### ISSUE TITLE
401 Client Error

### ISSUE THREAD

**Issue by lcl-367** [B1ue1nWh1te/Poseidon#1]
最近在练习blockchain，发现师傅的写的工具，借鉴师傅的工具来练习web3，但在使用中发现，连接一些私链(一些比赛中的)时，凡是涉及到buildTransaction时，都会报401 Client Error，而在chainflag靶场则不会，经测试在buildTransaction()中加上gasPrice就不会，想师傅解答一下（刚学习，很多还不懂
如部署合约的代码
`DeployingContract.constructor(*Arguments).buildTransaction({"value": Value})`会报错
`DeployingContract.constructor(*Arguments).buildTransaction({"gasPrice": self.Net.eth.gas_price,"value": Value})`则不会

**Comment by B1ue1nWh1te** [comment]
谢谢你的反馈及修改建议，这个问题确实是存在的，因为大部分题目会禁用很多链上API，导致获取maxFeePerGas等参数时会报错，我之前是通过修改web3.py中的与EIP-1559相关部分代码来临时解决，但如果你提到的这种方法能够有效解决的话将会非常方便，我会在下个版本中进行修改。

**Comment by lcl-367** [comment]
其实我不太懂，只是胡乱测试出来的，感谢师傅的工具和博客让我学到了很多
