### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by tumiao233** [B1ue1nWh1te/Poseidon#4]
I install poseidon with # pip install poseidon-python ，but when I run it . 'ImportError: cannot import name 'geth_poa_middleware' from 'web3.middleware'' occurs

**Comment by B1ue1nWh1te** [comment]
可能是由于web3库有较大更新 而本库太久未更新 计划在11月前发一个新版本

**Comment by tumiao233** [comment]
> 可能是由于web3库有较大更新 本库太久未更新 计划在10月7日前发一个新版本

非常感谢，我昨天将web3库的版本回退到6.x暂时可以使用了

**Comment by B1ue1nWh1te** [comment]
全新版本v2.0.0已发布 对依赖库版本进行了约束 应该能解决这一问题
